site_name: FavoriteFiles Documentation
repo_url: https://github.com/facelessuser/FavoriteFiles
site_description: Sublime Text plugin for saving and accessing favorite files.
copyright: Copyright &copy; 2011 - 2015 <a href="https://github.com/facelessuser">Isaac Muse</a>
pages:
  - About FavoriteFiles: index.md
  - Installation: installation.md
  - User Guide: usage.md
  - Contributing &amp; Support: contributing.md
  - License: license.md
theme: readthedocs
theme_dir: doc_theme
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.smarty
  - markdown.extensions.nl2br
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.githubemoji
  - pymdownx.tasklist
  - pymdownx.progressbar
  - pymdownx.headeranchor
